### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by Lilmac12312** [lol768/XenForo-MCASSOC#11]
There was an error while associating your account.
Additional details: signature invalid

Help please?

**Comment by Lilmac12312** [comment]
Interesting, as soon as I put the "insecure" mode on it worked without any problems.

**Comment by lol768** [comment]
Morning!

Did you sign up over at https://mcassoc.lukegb.com/ and tell the addon the shared key etc?

**Comment by Lilmac12312** [comment]
I sure did. I put the shared key in "site id".

**Comment by lol768** [comment]
Ah, right. Does it work if you put the shared key into the "shared secret" box and the domain name you verified on mcassoc.lukegb.com into the "Site ID" box?

**Comment by Lilmac12312** [comment]
Yes. That works fine. (Removed insecure mode) and all works fine now. Do you know what the issue was?

**Comment by lol768** [comment]
Yes, the shared key doesn't go in the site ID box (the site ID goes in the site ID box, instead).

Is your site public? If so, how long was it left in a state where the site id was set to the shared secret?

**Comment by Lilmac12312** [comment]
My site is public, yes. Maybe less than 12 hours.

**Comment by lol768** [comment]
Okay, that's unlikely to have been an issue.
