### ISSUE TITLE
Unable to call API

### ISSUE THREAD

**Issue by xGamingDudex** [lol768/XenForo-MCASSOC#13]
So it might be me doing something wrong here but I can't seem to get the API working. Everything else on the add-on seems to be running fine, and currently running version 1.02.

I have enabled the API in the "http://<domain>/admin.php?options/list/associationMcOpts" and set the token to something simple as "abc" or "abc123". Then I try to query the api with "http://<domain>/mc-association/api/listAll&token=abc" but it just results in "- Error
The requested page could not be found."

I have tried with multiple different tokens, have tried disable/enable the api options multiple times. Even checked the xf_option table and found that option_id="mcAssocApiEnable" and option_value=1 so it is definitely enabled on the SQL backend.

Any help would be much appreciated, would really like to get our forum integrated into our mc network.

**Comment by lol768** [comment]
Just wanted to post a comment to say I'll try and look into this later tonight or tomorrow. Thanks for the detailed issue report.

Cheers.

**Comment by lol768** [comment]
A request to http://127.0.0.1/xf_latest/index.php?mc-association/api/lookupUserById&uid=1&token=123 works fine for me.

 It's worth noting the index.php is often required (and it's not included in the API doc since a lot of people have their webserver remove the need for the index.php to be present in the URL).

**Comment by xGamingDudex** [comment]
Thanks, it seems that adding the index.php? fixed it. May I suggest adding that to the API page for others to read too ;)
