### ISSUE TITLE
Error: Please specify a hexadecimal string with Even Length

### ISSUE THREAD

**Issue by FoxInFlame** [lol768/XenForo-MCASSOC#14]
I get ↑ the error above, when trying to set the options for MCAssoc.
Here is a screenshot of my options page,
![screenshot 2015-08-30 at 09 32 45](https://cloud.githubusercontent.com/assets/7716215/9566172/1c4f4592-4efa-11e5-8df2-e6b130112b58.png)

and here is the error: 
![screenshot 2015-08-30 at 09 33 45](https://cloud.githubusercontent.com/assets/7716215/9566175/3bd37866-4efa-11e5-898b-0650c08deefb.png)

How can I fix this, and what is the issue? I have exactly 6 letters/numbers on all the hexadecimal strings, not including the hashtag. What am I doing wrong?

**Comment by lol768** [comment]
`asdasd` is not a valid hexadecimal string.

**Comment by FoxInFlame** [comment]
But even if I change that. It still shows the error. Same error as before. "Please specify a valid hexadecimal string with even length"
![screenshot 2015-08-30 at 21 51 18](https://cloud.githubusercontent.com/assets/7716215/9569141/530e8004-4f61-11e5-9e5e-9237afdfef14.png)

**Comment by lol768** [comment]
`myPassword` is still not a valid hexadecimal string.

Try `abcdefabcdef`

**Comment by FoxInFlame** [comment]
Now it worked. What is the difference? Is it the letters I use? Hexadecimal, still don't get it.

**Comment by lol768** [comment]
Hexadecimal as a base commonly uses the characters 0-9, a-f to represent numeric values. ANy characters outside this range are not allowed.

**Comment by FoxInFlame** [comment]
Thank you for the support!
