### ISSUE TITLE
Hiding instance secret from user

### ISSUE THREAD

**Issue by SystemUpdate** [lol768/XenForo-MCASSOC#19]
Hello,

I somehow when testing managed to make the application throw an invalid signature error. This resulted in my instance secret being displayed to me, or a user who somehow manages to come across this error. I'm suggesting that it logs it to the XenForo server logs instead of displaying it to the user.

I don't know how much damage someone can do if they got hold of the instance secret, but I assume they can do some unless it wouldn't be a secret.

**Comment by lol768** [comment]
https://github.com/lol768/XenForo-MCASSOC/blob/master/ControllerPublic/Confirm.php#L51

```php
 return $this->responseView('AssociationMc_ViewPublic_Error', 'association_error', array("exceptionMessage" => ($isAdmin) ? $message : "Please contact an administrator for more information."));
```

Key bit here is the `$isAdmin` ternary.

**Comment by lol768** [comment]
Let me know if I can close, or if you still think this is problematic :)

**Comment by SystemUpdate** [comment]
Oh I see.

Many thanks

**Comment by lol768** [comment]
No problem, thanks for the report!
