### ISSUE TITLE
$entry.minecraft_uuid

### ISSUE THREAD

**Issue by xeru** [lol768/XenForo-MCASSOC#21]
I'm trying to figure out what's preventing the "minecraft_uuid" variable from being printed in the profile tab (template association_profile_tab_content).

It seems like it might be an unprintable data type (binary), but it's showing in the ACP. I'm wondering if I'll have to process it to a string in PHP and add a callback to fix this or if there's an easier way. If not, I'd make the suggestion to a variable for a string/printable UUID built-in. Main application for such an addition would be adding links to the profile entries to lookup the account by UUID rather than last username. This will prevent confusion in the event of a name change or previously-owned name.

Thank you.

**Comment by lol768** [comment]
Hey,

For that template I pass it a "mcEntries" array which is an array of rows direct from the database.

You're correct in that minecraft_uuid is stored as binary data in the database for storage efficiency. For the ACP I just manually convert them all to text:

https://github.com/lol768/XenForo-MCASSOC/blob/master/ControllerAdmin/User.php#L24

```php
foreach ($entries as &$entry) {
    $entry['minecraft_uuid'] = bin2hex($entry['minecraft_uuid']);
    $entry['associated'] = true;
}
```

I can look at doing the same with the other templates, if that would solve your problem?

**Comment by xeru** [comment]
Yes, that would be fantastic. Thank you.

**Comment by lol768** [comment]
Sorry for the delay on this, trying to get a usable development environment up and running after moving.

**Comment by lol768** [comment]
Hello @xeru,

If you get a moment, could you try the pre-release over at https://github.com/lol768/XenForo-MCASSOC/releases/tag/1.1.1? In testing, I was able to do some simple stuff like displaying the hex-encoded UUID in a tooltip:

![](https://lol768.com/i/CpMx72wLfZc-vg)

Cheers.

**Comment by xeru** [comment]
Fantastic! I've updated from that commit, and it does exactly what I needed. Thank you!

**Comment by lol768** [comment]
Great stuff, I'll close this issue :)
