### ISSUE TITLE
Heximal error

### ISSUE THREAD

**Issue by TheCreeperCow** [lol768/XenForo-MCASSOC#22]
When i try to update the settings it keeps saying i need to put in a even heximal string while i am just using the default color settings

**Comment by lol768** [comment]
You need to choose a hexadecimal instance secret if you haven't already. An easy way of getting something with enough entropy is to use [this site](http://www.md5.cz/) - just type a passphrase (don't need to remember it) in the box and click the button.

If you think you have, please screenshot the config page and attach it so I can see it.
