### ISSUE TITLE
I want more accounts to be linked !

### ISSUE THREAD

**Issue by Voraxe** [lol768/XenForo-MCASSOC#23]
Hey, I want at least 5 Accounts to be linked in my system, Can someone help me?

**Thanks!**

**Comment by lol768** [comment]
I need some more information than that, @Voraxe.

What's wrong with the current build? Do you want to display more than are currently displayed next to the user's posts? All asccounts should be displayed in the tab on the profile.

**Comment by Voraxe** [comment]
No, Like you did for mc-market.org, I want that same thing to be done! :dancing_men:

**Comment by lol768** [comment]
Update.
https://github.com/lol768/XenForo-MCASSOC/releases
