### ISSUE TITLE
Linking Isee

### ISSUE THREAD

**Issue by Voraxe** [lol768/XenForo-MCASSOC#24]
I want to link all of users Minecraft Account with nameMC so 

If user 1 attaches his account "Minecraft" it will link his account to "https://namemc.com/Minecraft/1"
That link is available on user 1's all posts, (right sidebar) as it is now.
and is also available to click on the user 1's profile tab as well.

**Comment by lol768** [comment]
Should be possible with a (few) template edit(s). How familiar are you with XenForo's template system, @Voraxe?

**Comment by Voraxe** [comment]
Just basic, I am not a coder but I can do stuff related to coding.

**Comment by lol768** [comment]
Okay, so some steps:

* Find the association_profile_sidebar template and edit it:
* Change `<dd><img src="{xen:helper headimage, $entry.last_username, 12}" class="mcAccAvatarLarger"></img> {$entry.last_username}</dd>` to `<dd><a href="https://namemc.com/s?q={$entry.last_username}"><img src="{xen:helper headimage, $entry.last_username, 12}" class="mcAccAvatarLarger"></img> {$entry.last_username}</a></dd>`

* Find the association_thread_post template and edit it:
* Change `<span class="mcAccText"><img src="{xen:helper headimage, {$entry}, 11}" class="mcAccAvatar"></img> {$entry}</span>` to `<span class="mcAccText"><a href="https://namemc.com/s?q={$entry}"><img src="{xen:helper headimage, {$entry}, 11}" class="mcAccAvatar"></img> {$entry}</a></span>`

**Comment by Voraxe** [comment]
Thanks it works! <3
