### ISSUE TITLE
Associated Player profile avatar/name is disapearing random with latest XF

### ISSUE THREAD

**Issue by xion87** [lol768/XenForo-MCASSOC#26]
i noticed player name toolbox of associationmc is random disapearing for some user, or sometimes it don't appaer. it started to happen with latest 2 xenforo updates....

Association_thread_post
https://hastebin.com/felemifuju.xml

**Comment by lol768** [comment]
Which version of XenForo are you using in particular? How can I reproduce the problem - are there steps I can follow?

**Comment by xion87** [comment]
Example https://trollandia.it/community/members/orangea7.4959/ Itsathat he associated an account
Intead here avatar box is not appaering for him
![immagine](https://cloud.githubusercontent.com/assets/3611852/23610846/9c9c8e24-0274-11e7-9545-4a203f517093.png)

I am using Xenforo 1.5.12

**Comment by xion87** [comment]
Nvm i was using a dev version, i just dowgrade to old version and the issue seem gone for now

**Comment by lol768** [comment]
A dev version of the addon?

**Comment by xion87** [comment]
i was using version 1.1.1 (tag version) but is more like that ii broke something with the upgrade/templates
