### ISSUE TITLE
Change skin link is broken

### ISSUE THREAD

**Issue by Malachiel87** [lol768/XenForo-MCASSOC#35]
When i click "change skin" it redirect to this site: https://minecraft.net/en-us/login/?return_url=https%3A%2F%2Fminecraft.net%2Fen-us%2Fprofile%2Fskin%2Fremote%3Furl%3Dhttps%253A%252F%252Fwww.googleapis.com%252Fdownload%252Fstorage%252Fv1%252Fb%252Fmcassoc-ng.appspot.com%252Fo%252Fc883f59d66214243b64b3781d9fd9530.png%253Fgeneration%253D1551546432043876%2526alt%253Dmedia

and say 502 bad gateway

**Comment by lol768** [comment]
This is part of `lukegb/mcassoc` rather than this add-on:

https://github.com/lukegb/mcassoc/blob/45c829c4616bf326678cfaf7958142574fde8d83/templates/perform.html#L206

But it sounds like a Mojang issue

**Comment by lol768** [comment]
Potentially fixed in: https://github.com/lukegb/mcassoc/commit/a1820d72b692307bef222bb901fd79887c38c7ae

**Comment by Malachiel87** [comment]
oh sorry i posted the issue in the wrong place, anyway that fix is live?

**Comment by lol768** [comment]
I've sent Luke a twitter DM to ask him if he can push my fix to produciton

**Comment by lol768** [comment]
@xion87 Can you reproduce now?

**Comment by Malachiel87** [comment]
yeah seem fixed time ago sorry for missed the ticket ^^
