### ISSUE TITLE
Fix "just-created" messages not showing association info

### ISSUE THREAD

**Issue by lol768** [lol768/XenForo-MCASSOC#7]
@PunKeel on [#3](https://github.com/lol768/XenForo-MCASSOC/issues/3#issuecomment-75988578)
>Hi,

>When you reply to a PM, the "dynamically added block" (with your sent message) does not include the Minecraft part.
Hadn't time to try myself to fix it, but I report here meanwhile

@lol768 on [#3](https://github.com/lol768/XenForo-MCASSOC/issues/3#issuecomment-76017936)
>I'm aware of this one since it's something I have looked into without much luck in the past. This should also probably apply to messages made in threads too. I'll have another look at some point in the future but since XenForo doesn't do much in the way of developer documentation I find writing addons for it difficult.

**Comment by PunKeel** [comment]
After some digging, (using PM, haven't tested with threads) : the ajax request returns the raw html part, rendered from `conversation_view_new_messages`, itself looping over `conversation_message`, containing an `<xen:include template="message">` (and `message` itself calling the `message_user_info` template, and so your modification)..


In a word, everything is like when it's not AJAX. :)

Epicness level ... 9000 ?

**Comment by lol768** [comment]
@PunKeel That's really helpful, thanks!

I take it you meant `actionView()` since I can't see an `actionIndex()` in that controller (or at least a function that I am overriding). In any case, I think you're hit the nail on the head with the AJAX-y stuff not causing that function to be called. 

I'm guessing I need to look at overriding `actionInsertReply()` from `XenForo_ControllerPublic_Conversation`. Will do some experimentation.

Thanks again.

**Comment by PunKeel** [comment]
Really ?

**Comment by lol768** [comment]
Yup! Thanks a bunch for your help. Release will be on XenForo's site soon, too.

https://github.com/lol768/XenForo-MCASSOC/releases/tag/1.0.1

**Comment by PunKeel** [comment]
Patch applied & _bug_ fixed :D

**Comment by lol768** [comment]
Awesome, let me know if you run into any other issues or have any requests.

**Comment by PunKeel** [comment]
Simple one, not linked to your plugin but more to Xenforo: how am I supposed to update a plugin (I've manually applied the patch). I've seen a plugin that could handle it, but it requires my Xenforo credentials, and I don't really like it ... [I grant myself the right to ask here because you _could_ include an auto updater, but it looks like it's uncommon in the great Xenforo's world ...]

**Comment by lol768** [comment]
The way I do it locally is like this:

* In $XenForo_Root$/library/ I've `git clone`'d this repository. You only need to do this once.
* When I want to update the code, I simply do a `git pull` to pull and merge in all of the remote changes.
* If the XML file has changed, I'll use XenForo's 'upgrade addon' form and tell it to use the XML file in the `AssociationMc` folder (the cloned git repository).

What would be nice is automating the final part - I could look into a script to do the pulling and upgrading in one step, perhaps. 

Yeah, auto-updaters are uncommon and with the latest drama over addons phoning home I'd probably prefer not to risk integrating one. 

Do you have SSH access to the server you host the forums on? None of the above is going to work if you don't, unfortunately - and I know a lot of people in the XenForo world *do* just rely solely on shared hosting and use FTP etc to upload the files when things change.

**Comment by PunKeel** [comment]
I own my dedicated server, so I do have git, ssh ... and I'll stick with this method :-)

Thanks again !

**Comment by PunKeel** [comment]
Oh, talking about drama, I use one of their _free_ plugins (downloaded yesterday, never ever heard about the drama ... And I don't really care, the source code seemed clean at first sight) that live refreshing. And it doesn't work with your addon :(
The called url being `{/forum}/threads/thread-update.json`, I think the issue is the same as in this issue ... but I'm unsure if it's a good idea to add every route from every addon ... Maybe is there a "global" route for this purpose ? 

(If no content is added, the reply is 
```json
{"templateHtml":"","css":"","js":"","_visitor_conversationsUnread":"0","_visitor_alertsUnread":"0"}
```)

**Comment by lol768** [comment]
>(btw, as a side note ... full command to be done in ./library/ is git clone https://github.com/lol768/XenForo-MCASSOC.git AssociationMc, I think it wouldn't work with the repo name)

Yeah, that's a good point - I'm bad with consistency sometimes..

Anything that adds new methods of grabbing the current posts info instead of interacting with (i.e. extending) the normal ways of grabbing new posts and/or threads is probably going to conflict with how I'm doing things. I'd need to look into the addon itself, since unfortunately they could be doing it in a number of different ways. The only way I can think of doing it that would be 'global' would be to use a template hook instead of extending the controller methods. Unfortunately, this would be a big performance hit (i.e. one query per post) because I can't just use one query for the entire page any more.

**Comment by PunKeel** [comment]
I thought they used some kind of common api, like adding the format at the end of the url.

But no, they call their own route (`{/forum}/threads/thread-update.json` is the true url, and so does not include the thread id ...)

Thanks,
